### PR TITLE
Update mbed-mesh-api to version 1.0.0

### PR DESCRIPTION
**Pull request by bremoran**
cc @SeppoTakalo @bogdanm

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by SeppoTakalo** [comment]
+1.
I think it should be safe to remove the legacy "nanostack" because you pumped up the Major version, so any module that is not yet updated, should change the references while going to 1.0.0.
(And to my knowledge, I have not seen any references to "similarTo": "nanostack")

**Comment by bremoran** [comment]
@SeppoTakalo understood.  I will push a new change that removes the nanostack target

**Comment by bremoran** [comment]
Unless there are any objections, I will merge this.

**Pull request merged**
