### PR TITLE
Update Mesh-API to next Major version

### PR DESCRIPTION
**Pull request by SeppoTakalo**
Required by https://github.com/ARMmbed/mbed-client-example-6lowpan/pull/54

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
CC: @bremoran

**Comment by bremoran** [comment]
Does this contain API-breaking changes?

**Comment by SeppoTakalo** [comment]
Basically it just pull in the breaking API changes for Nanostack so therefore I pumped up the major version.

**Comment by bremoran** [comment]
Do I need to increase the major version of SAL for this change?

**Comment by SeppoTakalo** [comment]
No. I pumped up the major of mesh-api, nanostack and atmel-driver.
The mesh-api did not basically change, so it is enough that you do just patch version update.

**Pull request merged**
