### PR TITLE
Add test dependencies

### PR DESCRIPTION
**Pull request by stegut01**
Move test related dependencies to "testDependencies"

test report:
```
mbedgt: test suite report:
+---------------+---------------+-------------------------+--------+--------------------+-------------+
| target        | platform_name | test suite              | result | elapsed_time (sec) | copy_method |
+---------------+---------------+-------------------------+--------+--------------------+-------------+
| frdm-k64f-gcc | K64F          | sal-test-stack-registry | OK     | 10.57              | shell       |
+---------------+---------------+-------------------------+--------+--------------------+-------------+
mbedgt: test suite results: 1 OK
mbedgt: test case report:
+---------------+---------------+-------------------------+---------------------------------+--------+--------+--------+--------------------+
| target        | platform_name | test suite              | test case                       | passed | failed | result | elapsed_time (sec) |
+---------------+---------------+-------------------------+---------------------------------+--------+--------+--------+--------------------+
| frdm-k64f-gcc | K64F          | sal-test-stack-registry | Test the socket stack registery | 1      | 0      | OK     | 0.09               |
+---------------+---------------+-------------------------+---------------------------------+--------+--------+--------+--------------------+
mbedgt: test case results: 1 OK
mbedgt: completed in 11.54 sec
```

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
Note: This PR is response for https://github.com/ARMmbed/greentea/issues/101.

@bremoran Please review :)

**Comment by PrzemekWirkus** [comment]
Weird, ```jenkins-internal``` shows status failed but both builds are fine!
* https://jenkins-internal.mbed.com/job/sal/42/label=gcc,target=frdm-k64f-gcc/console
* https://jenkins-internal.mbed.com/job/sal/42/label=armcc,target=frdm-k64f-armcc/console

**Comment by bremoran** [comment]
It's a java exception inside jenkins. I'll rerun the build.

**Comment by stegut01** [comment]
testDependencies already added

**Pull request closed without merging**
