### PR TITLE
Fix naming error for Nagle option

### PR DESCRIPTION
**Pull request by bremoran**
cc @bogdanm @niklas-arm @SeppoTakalo @artokin 

I don't believe that the Nagle option has been used anywhere yet, so this should be safe to rename.

@SeppoTakalo & @artokin can you confirm that Nagle hasn't been used in sal-stack-nanostack?

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by bremoran** [comment]
cc @LiyouZhou

**Comment by LiyouZhou** [comment]
Got it cheers.
+1

**Comment by niklas-arm** [comment]
+1

**Comment by artokin** [comment]
Sorry for delay, nagle option is not used in nanostack.

**Pull request merged**
