### PR TITLE
Changeset fix network deps

### PR DESCRIPTION
**Pull request by bogdanm**
Do not merge yet.

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by bogdanm** [comment]
**Changeset**: update dependencies of network related modules

**Changes in set**:

- ARMmbed/sal-iface-eth/pull/8
- ARMmbed/sal-driver-lwip-k64f-eth/pull/6
- ARMmbed/sal-stack-lwip/pull/24
- **ARMmbed/sal/pull/22** (this change)
- ARMmbed/sockets/pull/30

**Top level change**: ARMmbed/sockets/pull/30

**Comment by bogdanm** [comment]
Ready to merge, but **please only merge the whole changeset**. @bremoran @0xc0170

**Comment by bremoran** [comment]
+1

**Comment by bogdanm** [comment]
@bremoran: please publish version 0.4.0, I'm not a module owner.

**Pull request merged**
