### PR TITLE
Updated dependency on major 1 of greentea-client

### PR DESCRIPTION
**Pull request by bogdanm**

### CODE REVIEW

**Comment by bogdanm** [comment]
Major version 1 of greentea-client was not published yet, but this change is backwards compatible.
The intention is to release a new *minor* version of this module once this PR is merged.
@bremoran

**Comment by bremoran** [comment]
+1

**Comment by bremoran** [comment]
-1
This is a test dependency

**Comment by bogdanm** [comment]
I didn't change the type of dependency, only its version spec. Looks like you're talking about a different issue.

**Comment by bogdanm** [comment]
I forced-pushed a version that declares unity` and `greentea-client` as test dependencies. Please review again.

**Comment by bremoran** [comment]
+1

**Pull request merged**
