### PR TITLE
Switch to config dependency.

### PR DESCRIPTION
**Pull request by bremoran**
Also update sal-stack-lwip dependency

cc @bogdanm

### CODE REVIEW

**Comment by miklis** [comment]
Build finished. No test results found.

**Comment by bogdanm** [comment]
Looks good, but I just realized that it exhibits the same issue with incompatible targets as the pin config stuff. If an older version of (say) `mbed-example-network` needs to be compiled and uses the new target definition, won't it fail? (not a problem with this change in particular, but more with the whole idea of "incompatible targets")

**Comment by bremoran** [comment]
@bogdanm In this case, this will be a minor version bump anyway, so it should be fine; the new version of the target has already been published.  More important is that the target still defines lwip in the similar-to field, so the new target works with older modules.

**Comment by bogdanm** [comment]
Great, that'll work then. +1.

**Pull request merged**
