### PR TITLE
Import four inet_address functions from

### PR DESCRIPTION
**Pull request by bremoran**
Add support for converting inet addresses to strings and vice versa

### CODE REVIEW

**Comment by bremoran** [comment]
@bogdanm @niklas-arm @0xc0170

**Comment by 0xc0170** [comment]
Shall also license files be updated, as I see there's apache at the moment in this module ?

**Comment by bogdanm** [comment]
> Shall also license files be updated, as I see there's apache at the moment in this module ?

+1. Ideally, the origin of the files should also be stated somewhere, in case someone ever needs to get a newer version of these files from their original project (if this is an option).
That said, why are we adding `.nocompile` files ? Seems a bit weird. Isn't it better to wait until we have something that actually works and compiles?

**Comment by bremoran** [comment]
I'll get the license files included.

You're right, @bogdanm they shouldn't have the .nocompile. The reason for that is that these files cannot be used unmodified. They depend on some header files we don't have and they also require some structures that we don't have. The changes are small, but they do require modification.

**Comment by bremoran** [comment]
I suggest reviewing each patch in isolation, otherwise this is unmanageable.

**Comment by autopulated** [comment]
For future reference you can use `.yotta_ignore` instead of renaming things to .nocompile :smile:

**Comment by niklas-arm** [comment]
+1.

**Pull request merged**
